development:
  host: localhost
  database: hsm_production

# temporarily use hsm_prod so we can look at production problems in staging.
#  database: showmanager_development

test:
  host: localhost
  database: showmanager_test

# set these environment variables on your prod server
production:
  host: localhost
  database: hsm_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
