require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShowItemsController do

  # This should return the minimal set of attributes required to create a valid
  # ShowItem. As you add validations to ShowItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShowItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all show_items as @show_items" do
      show_item = ShowItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:show_items).should eq([show_item])
    end
  end

  describe "GET show" do
    it "assigns the requested show_item as @show_item" do
      show_item = ShowItem.create! valid_attributes
      get :show, {:id => show_item.to_param}, valid_session
      assigns(:show_item).should eq(show_item)
    end
  end

  describe "GET new" do
    it "assigns a new show_item as @show_item" do
      get :new, {}, valid_session
      assigns(:show_item).should be_a_new(ShowItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested show_item as @show_item" do
      show_item = ShowItem.create! valid_attributes
      get :edit, {:id => show_item.to_param}, valid_session
      assigns(:show_item).should eq(show_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShowItem" do
        expect {
          post :create, {:show_item => valid_attributes}, valid_session
        }.to change(ShowItem, :count).by(1)
      end

      it "assigns a newly created show_item as @show_item" do
        post :create, {:show_item => valid_attributes}, valid_session
        assigns(:show_item).should be_a(ShowItem)
        assigns(:show_item).should be_persisted
      end

      it "redirects to the created show_item" do
        post :create, {:show_item => valid_attributes}, valid_session
        response.should redirect_to(ShowItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved show_item as @show_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShowItem.any_instance.stub(:save).and_return(false)
        post :create, {:show_item => {}}, valid_session
        assigns(:show_item).should be_a_new(ShowItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShowItem.any_instance.stub(:save).and_return(false)
        post :create, {:show_item => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested show_item" do
        show_item = ShowItem.create! valid_attributes
        # Assuming there are no other show_items in the database, this
        # specifies that the ShowItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShowItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => show_item.to_param, :show_item => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested show_item as @show_item" do
        show_item = ShowItem.create! valid_attributes
        put :update, {:id => show_item.to_param, :show_item => valid_attributes}, valid_session
        assigns(:show_item).should eq(show_item)
      end

      it "redirects to the show_item" do
        show_item = ShowItem.create! valid_attributes
        put :update, {:id => show_item.to_param, :show_item => valid_attributes}, valid_session
        response.should redirect_to(show_item)
      end
    end

    describe "with invalid params" do
      it "assigns the show_item as @show_item" do
        show_item = ShowItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShowItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => show_item.to_param, :show_item => {}}, valid_session
        assigns(:show_item).should eq(show_item)
      end

      it "re-renders the 'edit' template" do
        show_item = ShowItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShowItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => show_item.to_param, :show_item => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested show_item" do
      show_item = ShowItem.create! valid_attributes
      expect {
        delete :destroy, {:id => show_item.to_param}, valid_session
      }.to change(ShowItem, :count).by(-1)
    end

    it "redirects to the show_items list" do
      show_item = ShowItem.create! valid_attributes
      delete :destroy, {:id => show_item.to_param}, valid_session
      response.should redirect_to(show_items_url)
    end
  end

end
