require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TroupesController do

  # This should return the minimal set of attributes required to create a valid
  # Troupe. As you add validations to Troupe, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TroupesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all troupes as @troupes" do
      troupe = Troupe.create! valid_attributes
      get :index, {}, valid_session
      assigns(:troupes).should eq([troupe])
    end
  end

  describe "GET show" do
    it "assigns the requested troupe as @troupe" do
      troupe = Troupe.create! valid_attributes
      get :show, {:id => troupe.to_param}, valid_session
      assigns(:troupe).should eq(troupe)
    end
  end

  describe "GET new" do
    it "assigns a new troupe as @troupe" do
      get :new, {}, valid_session
      assigns(:troupe).should be_a_new(Troupe)
    end
  end

  describe "GET edit" do
    it "assigns the requested troupe as @troupe" do
      troupe = Troupe.create! valid_attributes
      get :edit, {:id => troupe.to_param}, valid_session
      assigns(:troupe).should eq(troupe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Troupe" do
        expect {
          post :create, {:troupe => valid_attributes}, valid_session
        }.to change(Troupe, :count).by(1)
      end

      it "assigns a newly created troupe as @troupe" do
        post :create, {:troupe => valid_attributes}, valid_session
        assigns(:troupe).should be_a(Troupe)
        assigns(:troupe).should be_persisted
      end

      it "redirects to the created troupe" do
        post :create, {:troupe => valid_attributes}, valid_session
        response.should redirect_to(Troupe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved troupe as @troupe" do
        # Trigger the behavior that occurs when invalid params are submitted
        Troupe.any_instance.stub(:save).and_return(false)
        post :create, {:troupe => {}}, valid_session
        assigns(:troupe).should be_a_new(Troupe)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Troupe.any_instance.stub(:save).and_return(false)
        post :create, {:troupe => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested troupe" do
        troupe = Troupe.create! valid_attributes
        # Assuming there are no other troupes in the database, this
        # specifies that the Troupe created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Troupe.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => troupe.to_param, :troupe => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested troupe as @troupe" do
        troupe = Troupe.create! valid_attributes
        put :update, {:id => troupe.to_param, :troupe => valid_attributes}, valid_session
        assigns(:troupe).should eq(troupe)
      end

      it "redirects to the troupe" do
        troupe = Troupe.create! valid_attributes
        put :update, {:id => troupe.to_param, :troupe => valid_attributes}, valid_session
        response.should redirect_to(troupe)
      end
    end

    describe "with invalid params" do
      it "assigns the troupe as @troupe" do
        troupe = Troupe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Troupe.any_instance.stub(:save).and_return(false)
        put :update, {:id => troupe.to_param, :troupe => {}}, valid_session
        assigns(:troupe).should eq(troupe)
      end

      it "re-renders the 'edit' template" do
        troupe = Troupe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Troupe.any_instance.stub(:save).and_return(false)
        put :update, {:id => troupe.to_param, :troupe => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested troupe" do
      troupe = Troupe.create! valid_attributes
      expect {
        delete :destroy, {:id => troupe.to_param}, valid_session
      }.to change(Troupe, :count).by(-1)
    end

    it "redirects to the troupes list" do
      troupe = Troupe.create! valid_attributes
      delete :destroy, {:id => troupe.to_param}, valid_session
      response.should redirect_to(troupes_url)
    end
  end

end
